// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: Res.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResMsgType PBMsgType  `protobuf:"varint,1,opt,name=resMsgType,proto3,enum=PBMsgType" json:"resMsgType,omitempty"`
	ReqId      string     `protobuf:"bytes,2,opt,name=reqId,proto3" json:"reqId,omitempty"`
	ResTime    uint64     `protobuf:"varint,3,opt,name=resTime,proto3" json:"resTime,omitempty"` // UTC
	RetCode    int32      `protobuf:"varint,4,opt,name=retCode,proto3" json:"retCode,omitempty"` // ok=0
	RetMsg     string     `protobuf:"bytes,5,opt,name=retMsg,proto3" json:"retMsg,omitempty"`
	Payload    *anypb.Any `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // bytes payload = 6; // bug: js 无法执行序列化，改为 bytes
}

func (x *PBRes) Reset() {
	*x = PBRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Res_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRes) ProtoMessage() {}

func (x *PBRes) ProtoReflect() protoreflect.Message {
	mi := &file_Res_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRes.ProtoReflect.Descriptor instead.
func (*PBRes) Descriptor() ([]byte, []int) {
	return file_Res_proto_rawDescGZIP(), []int{0}
}

func (x *PBRes) GetResMsgType() PBMsgType {
	if x != nil {
		return x.ResMsgType
	}
	return PBMsgType_InvalidMsgType
}

func (x *PBRes) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *PBRes) GetResTime() uint64 {
	if x != nil {
		return x.ResTime
	}
	return 0
}

func (x *PBRes) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *PBRes) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

func (x *PBRes) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Res_proto protoreflect.FileDescriptor

var file_Res_proto_rawDesc = []byte{
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x05, 0x50, 0x42, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x50, 0x42, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Res_proto_rawDescOnce sync.Once
	file_Res_proto_rawDescData = file_Res_proto_rawDesc
)

func file_Res_proto_rawDescGZIP() []byte {
	file_Res_proto_rawDescOnce.Do(func() {
		file_Res_proto_rawDescData = protoimpl.X.CompressGZIP(file_Res_proto_rawDescData)
	})
	return file_Res_proto_rawDescData
}

var file_Res_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Res_proto_goTypes = []interface{}{
	(*PBRes)(nil),     // 0: PBRes
	(PBMsgType)(0),    // 1: PBMsgType
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_Res_proto_depIdxs = []int32{
	1, // 0: PBRes.resMsgType:type_name -> PBMsgType
	2, // 1: PBRes.payload:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Res_proto_init() }
func file_Res_proto_init() {
	if File_Res_proto != nil {
		return
	}
	file_MsgType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Res_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Res_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Res_proto_goTypes,
		DependencyIndexes: file_Res_proto_depIdxs,
		MessageInfos:      file_Res_proto_msgTypes,
	}.Build()
	File_Res_proto = out.File
	file_Res_proto_rawDesc = nil
	file_Res_proto_goTypes = nil
	file_Res_proto_depIdxs = nil
}
