// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: res/HeartbeatRes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResIndex int64 `protobuf:"varint,2,opt,name=resIndex,proto3" json:"resIndex,omitempty"`
}

func (x *HeartbeatRes) Reset() {
	*x = HeartbeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_res_HeartbeatRes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRes) ProtoMessage() {}

func (x *HeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_res_HeartbeatRes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRes.ProtoReflect.Descriptor instead.
func (*HeartbeatRes) Descriptor() ([]byte, []int) {
	return file_res_HeartbeatRes_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRes) GetResIndex() int64 {
	if x != nil {
		return x.ResIndex
	}
	return 0
}

var File_res_HeartbeatRes_proto protoreflect.FileDescriptor

var file_res_HeartbeatRes_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_res_HeartbeatRes_proto_rawDescOnce sync.Once
	file_res_HeartbeatRes_proto_rawDescData = file_res_HeartbeatRes_proto_rawDesc
)

func file_res_HeartbeatRes_proto_rawDescGZIP() []byte {
	file_res_HeartbeatRes_proto_rawDescOnce.Do(func() {
		file_res_HeartbeatRes_proto_rawDescData = protoimpl.X.CompressGZIP(file_res_HeartbeatRes_proto_rawDescData)
	})
	return file_res_HeartbeatRes_proto_rawDescData
}

var file_res_HeartbeatRes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_res_HeartbeatRes_proto_goTypes = []interface{}{
	(*HeartbeatRes)(nil), // 0: HeartbeatRes
}
var file_res_HeartbeatRes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_res_HeartbeatRes_proto_init() }
func file_res_HeartbeatRes_proto_init() {
	if File_res_HeartbeatRes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_res_HeartbeatRes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_res_HeartbeatRes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_res_HeartbeatRes_proto_goTypes,
		DependencyIndexes: file_res_HeartbeatRes_proto_depIdxs,
		MessageInfos:      file_res_HeartbeatRes_proto_msgTypes,
	}.Build()
	File_res_HeartbeatRes_proto = out.File
	file_res_HeartbeatRes_proto_rawDesc = nil
	file_res_HeartbeatRes_proto_goTypes = nil
	file_res_HeartbeatRes_proto_depIdxs = nil
}
